export const TPM_REGISTRATION_GRID_REQUEST = "TPM_REGISTRATION_GRID_REQUEST";
export const TPM_REGISTRATION_GRID_FAILURE = "TPM_REGISTRATION_GRID_FAILURE";
export const TPM_REGISTRATION_GRID_SUCCESS = "TPM_REGISTRATION_GRID_SUCCESS";

export const TPM_REGISTRATION_LIST_SUCCESS_DNF = "TPM_REGISTRATION_LIST_SUCCESS_DNF";
export const TPM_REGISTRATION_GRID_CLEAR = "TPM_REGISTRATION_GRID_CLEAR";
export const TPM_REGISTRATION_OFFICERS_VIEW_LIST_SUCCESS = "TPM_REGISTRATION_OFFICERS_VIEW_LIST_SUCCESS";
