export const GET_GENERAL_COMMENTS_REQUEST = "GET_GENERAL_COMMENTS_REQUEST";
export const GET_GENERAL_COMMENTS_FAILURE = "GET_GENERAL_COMMENTS_FAILURE";
export const GET_GENERAL_COMMENTS_SUCCESS = "GET_GENERAL_COMMENTS_SUCCESS";
export const GET_GENERAL_COMMENTS_CLEAR_STATE = "GET_GENERAL_COMMENTS_CLEAR_STATE";