export const CATCH_CERTIFICATE_VIEW_SUCCESS = "CATCH_CERTIFICATE_VIEW_SUCCESS";
export const CATCH_CERTIFICATE_SD_VIEW_SUCCESS = "CATCH_CERTIFICATE_SD_VIEW_SUCCESS";
export const CATCH_CERTIFICATE_VIEW_REQUEST = "CATCH_CERTIFICATE_VIEW_REQUEST";
export const CATCH_CERTIFICATE_VIEW_FAILURE = "CATCH_CERTIFICATE_VIEW_FAILURE";
export const CATCH_CERTIFICATE_VIEW_STOP_LOADER = "CATCH_CERTIFICATE_VIEW_STOP_LOADER";
export const INDEPENDENT_CATCH_CERTIFICATE_VIEW_SUCCESS = "INDEPENDENT_CATCH_CERTIFICATE_VIEW_SUCCESS";
export const CHANGE_CATCH_CERTIFICATE_STATUS_SUCCESS = "CHANGE_CATCH_CERTIFICATE_STATUS_SUCCESS";
