//update store information for edit and view case
export const UPDATE_STORE_OBJECT_ITEM_SUCCESS =
    "UPDATE_STORE_OBJECT_ITEM_SUCCESS";
export const UPDATE_STORE_OBJECT_ITEM_REQUEST =
    "UPDATE_STORE_OBJECT_ITEM_REQUEST";
export const UPDATE_STORE_OBJECT_ITEM_FAILURE =
    "UPDATE_STORE_OBJECT_ITEM_FAILURE";
