export const RELEASE_ORDER_VIEW_PHYSICAL_INSPECTION_SUCCESS =
    "RELEASE_ORDER_VIEW_PHYSICAL_INSPECTION_SUCCESS";
export const RELEASE_ORDER_DETAILED_VIEW_SUCCESS =
    "RELEASE_ORDER_DETAILED_VIEW_SUCCESS";
export const RELEASE_ORDER_VIEW_SUCCESS = "RELEASE_ORDER_VIEW_SUCCESS";
export const RELEASE_ORDER_VIEW_REQUEST = "RELEASE_ORDER_VIEW_REQUEST";
export const RELEASE_ORDER_VIEW_FAILURE = "RELEASE_ORDER_VIEW_FAILURE";
export const RELEASE_ORDER_CLEAR_STATE =
    "RELEASE_ORDER_CLEAR_STATE";
export const CHANGE_RELEASE_ORDER_STATUS_SUCCESS =
    "CHANGE_RELEASE_ORDER_STATUS_SUCCESS";
export const CHANGE_ITEMWISE_STATUS_SUCCESS = "CHANGE_ITEMWISE_STATUS_SUCCESS";

export const RELEASE_ORDER_RIGHTS_SUCCESS = "RELEASE_ORDER_RIGHTS_SUCCESS";
export const RELEASE_ORDER_RIGHTS_REQUEST = "RELEASE_ORDER_RIGHTS_REQUEST";


export const TPM_CallTreatment_History_SUCCESS = "TPM_CallTreatment_History_SUCCESS";
export const TPM_CallTreatment_History_REQUEST = "TPM_CallTreatment_History_REQUEST";
export const TPM_CallTreatment_History_FAILURE = "TPM_CallTreatment_History_FAILURE";
export const TPM_CallTreatment_History_CLEAR_STATE = "TPM_CallTreatment_History_CLEAR_STATE";