export const GET_TREATMENT_REQUEST_LIST = "GET_TREATMENT_REQUEST_LIST";
export const GET_TREATMENT_CERTIFICATE_DATA = "GET_TREATMENT_CERTIFICATE_DATA";

export const SELECTED_TAB = "SELECTED_TAB";
export const GET_IO_RIGHTS = "GET_IO_RIGHTS";

export const LOADING_PENDING_LIST = "LOADING_PENDING_LIST";

export const SET_IS_LOADING_FALSE = "SET_IS_LOADING_FALSE";
