// Dashboard Action Types
export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";
export const DASHBOARD_CLEAR_STATE = "DASHBOARD_CLEAR_STATE";

// Dashboard Switch User Role Action Types
export const DASHBOARD_SEPARATE_MENUS_SUCCESS = "DASHBOARD_SEPARATE_MENUS_SUCCESS";

export const DASHBOARD_FILTER_MENUS_SUCCESS = "DASHBOARD_FILTER_MENUS_SUCCESS";
export const DASHBOARD_SEARCH_MENUS_SUCCESS = "DASHBOARD_SEARCH_MENUS_SUCCESS";

// Dashboard Get Welcome Message Action Types
export const GET_WELCOME_MESSAGE_SUCCESS = "GET_WELCOME_MESSAGE_SUCCESS";
export const PAGE_TITLE = "PAGE_TITLE";
export const WEBOC_SESSION = "WEBOC_SESSION";

//NOTIFICATION TYPE ACTION
export const ADD_NOTIFICATION_ACTION = "ADD_NOTIFICATION_ACTION";
export const REMOVE_NOTIFICATION_TYPE = "REMOVE_NOTIFICATION_TYPE";

// Dashboard Get Dashboard Info Action Types
export const GET_DASHBOARD_INFO_SUCCESS = "GET_DASHBOARD_INFO_SUCCESS";

// Dashboard Unread Messages Action Types
export const GET_UNREAD_USER_MESSAGES_SUCCESS = "GET_UNREAD_USER_MESSAGES_SUCCESS";

// Dashboard Unread Alerts Action Types
export const GET_UNREAD_USER_ALERTS_SUCCESS = "GET_UNREAD_USER_ALERTS_SUCCESS";

// Dashboard Update User Role Action Types
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";

// Dashboard Update User Role Action Types
export const GET_LATEST_MESSAGES_SUCCESS = "GET_LATEST_MESSAGES_SUCCESS";
