export const GET_CITIES_BY_COUNTRY_SUCCESS = "GET_CITIES_BY_COUNTRY_SUCCESS";
export const GET_CITIES_BY_COUNTRY_FAILURE = "GET_CITIES_BY_COUNTRY_FAILURE";

export const GET_COLLECTORATE_CITIES_SUCCESS =
    "GET_COLLECTORATE_CITIES_SUCCESS";
export const GET_COLLECTORATE_CITIES_FAILURE =
    "GET_COLLECTORATE_CITIES_FAILURE";

export const SHARED_REQUEST = "SHARED_REQUEST";
export const SHARED_FAILURE = "SHARED_FAILURE";
export const SHARED_CLEAR_STATE = "SHARED_CLEAR_STATE";

export const GET_CUSTOMS_COLLECTORATE_FAILURE = "GET_CUSTOMS_COLLECTORATE_FAILURE";
export const GET_CUSTOMS_COLLECTORATE_SUCCESS = "GET_CUSTOMS_COLLECTORATE_SUCCESS";
export const GET_CUSTOMS_COLLECTORATE_REQUEST = "GET_CUSTOMS_COLLECTORATE_REQUEST";
