export const TEST_ACTION_TYPE = "TEST_ACTION_TYPE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CHECK_AUTHORIZED = "CHECK_AUTHORIZED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_TOKEN= "SET_TOKEN";
export const SET_INTERVAL= "SET_INTERVAL";

