export const GET_CREATESUBSCRIPTION_REQUEST = "GET_CREATESUBSCRIPTION_REQUEST";
export const GET_CREATESUBSCRIPTION_SUCCESS = "GET_CREATESUBSCRIPTION_SUCCESS";
export const GET_CREATESUBSCRIPTION_FAILURE = "GET_CREATESUBSCRIPTION_FAILURE";

export const GENERATE_PSID_SUCCESS = "GENERATE_PSID_SUCCESS";
export const GENERATE_PSID_REQUEST  = "GENERATE_PSID_REQUEST";
export const GENERATE_PSID_FAILURE = "GENERATE_PSID_FAILURE"
export const CLEAR_GENERATE_PSID = "CLEAR_GENERATE_PSID";
export const CLEAR_GET_CREATESUBSCRIPTION = "CLEAR_GET_CREATESUBSCRIPTION";
