export const FILE_REQUEST = "FILE_REQUEST";
export const FILE_FAILURE = "FILE_FAILURE";
export const FILE_DOWNLOAD_SUCCESS = "FILE_DOWNLOAD_SUCCESS";
export const GET_FILEPATH_SUCCESS = "GET_FILEPATH_SUCCESS";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS";
export const FILE_SECURE_DELETE_SUCCESS = "FILE_SECURE_DELETE_SUCCESS";
export const EDIT_FILES = "EDIT_FILES";
export const FILE_CLEAR_STATE = "FILE_CLEAR_STATE";
export const FILE_DOWNLOADED = "FILE_DOWNLOADED";
export const FILE_DELETE_SUCCESS_V2 = "FILE_DELETE_SUCCESS_V2";

export const FILE_UPLOAD_SUCCESS_V2 = "FILE_UPLOAD_SUCCESS_V2";
export const FILE_SUBTYPE_UPLOAD = "FILE_SUBTYPE_UPLOAD";

