export const resources_EN = {
    CreateUser_UserId_placeholder: "User ID",
    CreateUser_UserId_label: "User ID",
    CreateUser_FullName_placeholder: "Enter Name",
    CreateUser_FullName_label: "Name",
    CreateUser_CNIC_placeholder: "Enter CNIC Number",
    CreateUser_CNIC_label: "CNIC",
    CreateUser_Email_placeholder: "Enter Email Address",
    CreateUser_Email_Name: "Email",
    CreateUser_Email_label: "Email",
    CreateUser_Phone_placeholder: "Enter Phone Number",
    CreateUser_Phone_label: "Phone Number",
    CreateUser_Mobile_placeholder: "Enter Mobile Number",
    CreateUser_Mobile_label: "Mobile Number",
    CreateUser_City_placeholder: "Select City",
    CreateUser_City_label: "City",
    CreateUser_MailingAddress_placeholder: "Enter Mailing Address",
    CreateUser_MailingAddress_label: "Mailing Address",
    CreateUser_AddRole_button: "Add Role",
    CreateUser_UploadDocument_Hint:
        "Only .jpeg, .jpg, & .png file are allowed for uploading. File size max limit is 5MB.",

    GetUser_LoginId_label: "Login ID",
    GetUser_Email_label: "Email",
    GetUser_Cell_label: "Cell Number",
    GetUser_CNIC_label: "CNIC",
    GetUser_Phone_label: "Phone Number",
    GetUser_Mailing_Address_label: "Mailing Address",

    UserDetail_Status_label: "Status",
    UserDetail_Transfer_Remarks_label: "Remarks *",

    Report_MonthsNumber_label: "Months",
    Report_WeeksNumber_label: "Weeks",
    Report_FromDate_label: "From Date",
    Report_ToDate_label: "To Date",

    Report_WeeksNumber_validationMessage: "Weeks should be from 1 to 52",
    Report_MonthsNumber_validationMessage: "Months should be from 1 to 12",

    Report_WeeksNumber_placeholder: "Enter number of weeks",
    Report_MonthssNumber_placeholder: "Enter number of months",
    Report_FromDate_placeholder: "Select From Date",
    Report_ToDate_placeholder: "Select To Date",
    Report_Search_Weeks: "Weeks",
    Report_Search_Months: "Months",
    Report_Search_Year: "Years",
    Report_Search_daily: "Days",
    Report_Search_button: "Search",
    Report_Export: "Generate Report",
    Report_Export_PDF: "PDF",
    Report_Export_Excel: "Excel",
    Report_Export_CSV: "CSV",
    Report_Export_HTML: "HTML",

    Track_Document_Title: "Track Document",
    View_Activity_Log_Title: "View Activity Log",

    complete_Profile_lab_title_placeholder: "Enter Lab Site Name",
    complete_profile_lab_title_label: "Lab Site Name*",
    complete_profile_mailing_address_label: "Mailing Address*",
    complete_profile_mailing_address_placeholder: "Enter Mailing Address",
    complete_profile_association_address_label: "Association Address",
    complete_profile_association_address_placeholder: "Enter Association Address",
    complete_profile_email_address_1_label: "Email Address 1*",
    complete_profile_email_address_1_placeholder: "Enter Email Address 1",
    complete_profile_email_address_2_label: "Email Address 2",
    complete_profile_email_address_2_placeholder: "Enter Email Address 2",
    complete_profile_web_address_label: "Web Address*",
    complete_profile_web_address_placeholder: "Enter Web Address",
    complete_profile_extention_01_label: "Extension 01*",
    complete_profile_extention_01_placeholder: "Enter Extension 01",
    complete_profile_extention_02_label: "Extension 02",
    complete_profile_extention_02_placeholder: "Enter Extension 02",
    complete_profile_UAN_placeholder: "Enter UAN",
    complete_profile_UAN_label: "UAN*",
    complete_profile_direct_line_number_label: "Direct Line Number*",
    complete_profile_direct_line_number_placeholder: "Direct Line Number",

    complete_profile_lab_title: "name",
    complete_profile_association_center: "associationCenter",
    complete_profile_mailing_address: "mailingAddress",
    complete_profile_email_address_1: "emailAddress01",
    complete_profile_email_address_2: "emailAddress02",
    complete_profile_direct_line_number: "directLineNumber",
    complete_profile_UAN: "UAN",
    complete_profile_web_address: "website",
    complete_profile_extention_01: "extNumber01",
    complete_profile_extention_02: "extNumber02",

    complete_Profile_certification_name_placeholder: "Enter Title",

    complete_profile_certification_name_label: "Certification Title",
    complete_profile_certification_title: "name",

    complete_Profile_certification_description_placeholder: "Enter Description",

    complete_profile_certification_description_label: "Description",
    complete_profile_certification_description: "description",

    complete_Profile_accrediation_name_placeholder: "Enter Title",

    complete_profile_accrediation_name_label: "Accreditation Title",
    complete_profile_accrediation_title: "name",

    complete_Profile_accrediation_description_placeholder: "Enter Description",

    complete_profile_accrediation_description_label: "Description",
    complete_profile_accrediation_description: "description",

    complete_Profile_description_placeholder: "Enter Disclaimer",
    complete_Profile_description_label: "Disclaimer*",
    complete_profile_description: "disclaimer",

    complete_Profile_notes_placeholder: "Enter Notes",
    complete_Profile_notes_label: "Notes",
    complete_profile_notes: "notes",

    basic_info_agency_label: "Select Agency",
    basic_info_trade_type_label: "Trade Type",
    basic_info_importer_name_label: "Importer Name",
    basic_info_importer_address_label: "Importer Address",
    file_size: 5000000,
    file_size_validations: "Files above 5MB are not allowed",
    file_size_hint: "Supported file formats are  .jpeg, .jpg, .pdf & .png only. Maximum file size can be 5MB.",
    file_hint: "Only .jpeg, .jpg, .pdf & .png files are allowed for uploading. File size max limit is 5MB."
};