export const SET_SBFTP_JUILW = "SET_SBFTP_JUILW";
export const CLEAR_SBFTP_JUILW = "CLEAR_SBFTP_JUILW";
export const SET_MASKED_DATA = "SET_MASKED_DATA";
export const CLEAR_MASKED_DATA = "CLEAR_MASKED_DATA";
export const SET_OLD_MASKED_DATA = "SET_OLD_MASKED_DATA";