export const CREATE_EDIT_TREATMENT_ON_BOARD_DATA = "CREATE_EDIT_TREATMENT_ON_BOARD_DATA";
export const CREATE_EDIT_TREATMENT_ON_BOARD_DATA_CLEAR = "CREATE_EDIT_TREATMENT_ON_BOARD_DATA_CLEAR";
export const ADD_VALIDATION_MSG = "ADD_VALIDATION_MSG";
export const FILE_STORE_IN_FORM = "FILE_STORE_IN_FORM";
