export const INIT_TREATMENT_DETAIL_REQUEST = "INIT_TREATMENT_DETAIL_REQUEST";
export const INIT_TREATMENT_DETAIL_RESPONSE = "INIT_TREATMENT_DETAIL_RESPONSE";
export const BASIC_INFO_FAILURE = "BASIC_INFO_FAILURE";
export const BASIC_INFO_REQUEST = "BASIC_INFO_REQUEST";
export const INIT_TREATMENT_DETAIL_CLEAR = "INIT_TREATMENT_DETAIL_CLEAR";

export const INIT_TREATMENT_REQUEST_GET_TRADE_TYPE = "INIT_TREATMENT_REQUEST_GET_TRADE_TYPE";
export const INIT_TREATMENT_REQUEST_GET_EXPORT_NAME = "INIT_TREATMENT_REQUEST_GET_EXPORT_NAME";
export const INIT_TREATMENT_REQUEST_GET_EXPORT_ADDRESS = "INIT_TREATMENT_REQUEST_GET_EXPORT_ADDRESS";
export const INIT_TREATMENT_REQUEST_GET_COUNTRY_OF_ORIGIN = "INIT_TREATMENT_REQUEST_GET_COUNTRY_OF_ORIGIN";

// Common Actions
export const GET_AGENCY_DATA = "GET_AGENCY_DATA";
export const GET_COUNTRY_DATA = "GET_COUNTRY_DATA";
export const GET_COUNTRY_INCLUDING_PAK_DATA = "GET_COUNTRY_INCLUDING_PAK_DATA";

export const GET_IMPORTER_DATA = "GET_IMPORTER_DATA";
export const GET_IMPORTER_ADDRESS = "GET_IMPORTER_ADDRESS";

export const GET_CITY_DATA = "GET_CITY_DATA";
export const GET_SITE_DATA ="GET_SITE_DATA";
export const SET_HSCODE_LOADER = "SET_HSCODE_LOADER";

export const GET_HS_CODE_INFO = "GET_HS_CODE_INFO";

export const GET_UOM_BY_HS_CODE = "GET_UOM_BY_HS_CODE";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const GET_PORT_OF_LOADING = "GET_PORT_OF_LOADING";
export const SAVE_INITIATE_FORM_RESPONSE = "SAVE_INITIATE_FORM_RESPONSE";

export const GET_TREATMENT_TYPE = "GET_TREATMENT_TYPE"; 
export const GET_TREATMENT_TYPE_CLEAR = "GET_TREATMENT_TYPE_CLEAR";

export const GET_TREATMENT_PROVIDER = "GET_TREATMENT_PROVIDER"; 
export const GET_SHED_LOCATION_DATA_LIST = "GET_SHED_LOCATION_DATA_LIST"; 
export const GET_SUB_TREATMENT_TYPES = "GET_SUB_TREATMENT_TYPES"; 

export const GET_TREATMENT_TYPES_BY_TP_ID_REQUEST = "GET_TREATMENT_TYPES_BY_TP_ID_REQUEST"; 
export const GET_TREATMENT_TYPES_BY_TP_ID_FAILURE = "GET_TREATMENT_TYPES_BY_TP_ID_FAILURE";
export const GET_TREATMENT_TYPES_BY_TP_ID_SUCCESS = "GET_TREATMENT_TYPES_BY_TP_ID_SUCCESS"; 
export const GET_TREATMENT_TYPES_BY_TP_ID_CLEAR = "GET_TREATMENT_TYPES_BY_TP_ID_CLEAR";