export const GET_WORKLOAD_SUMMARY_REQUEST = "GET_WORKLOAD_SUMMARY_REQUEST";
export const GET_WORKLOAD_SUMMARY_SUCCESS = "GET_WORKLOAD_SUMMARY_SUCCESS";
export const GET_WORKLOAD_SUMMARY_FAILURE = "GET_WORKLOAD_SUMMARY_FAILURE";

export const GET_ALL_LAB_OFFICERS_REQUEST = "GET_ALL_LAB_OFFICERS_REQUEST";
export const GET_ALL_LAB_OFFICERS_SUCCESS = "GET_ALL_LAB_OFFICERS_SUCCESS";
export const GET_ALL_LAB_OFFICERS_FAILURE = "GET_ALL_LAB_OFFICERS_FAILURE";


export const RESET_WORKLOAD_SUMMARY_REDUCER_STATE = "RESET_WORKLOAD_SUMMARY_REDUCER_STATE";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAILURE = "USER_DETAIL_FAILURE";
export const UPDATE_PROFILE_PICTURE_SUCCESS = "UPDATE_PROFILE_PICTURE_SUCCESS";
