export const ITEMWISE_STATUS_REQUEST = "ITEMWISE_STATUS_REQUEST";

export const ITEMWISE_STATUS_FAILURE = "ITEMWISE_STATUS_FAILURE";

export const CHANGE_ITEMWISE_STATUS_SUCCESS = "CHANGE_ITEMWISE_STATUS_SUCCESS";

export const PENDING_ITEMS_COUNT = "PENDING_ITEMS_COUNT";
