//Clear App State
export const FLOW_STATE_UPDATE = "FLOW_STATE_UPDATE";
export const FLOW_STATE_CLEAR_STATE = "FLOW_STATE_CLEAR_STATE";

export const FORGOT_PASSWORD_CLEAR_STATE = "FORGOT_PASSWORD_CLEAR_STATE";
export const FORGOT_PASSWORD_VALIDATE_OTP_CLEAR_STATE = "FORGOT_PASSWORD_VALIDATE_OTP_CLEAR_STATE";
export const LINK_EXPIRED_CLEAR_STATE = "LINK_EXPIRED_CLEAR_STATE";

export const SUBSCRIPTION_FEE_CLEAR_STATE = "SUBSCRIPTION_FEE_CLEAR_STATE";

export const FORM_STATE_CLEAR_STATE = "FORM_STATE_CLEAR_STATE";
export const PAYMENT_PROCESS_CLEAR_STATE = "PAYMENT_PROCESS_CLEAR_STATE";

export const ALERT_CLEAR = "ALERT_CLEAR";
export const MODAL_ALERT_CLEAR = "MODAL_ALERT_CLEAR";
export const SUBSCRIPTION_INFORMATION_CLEAR_STATE = "SUBSCRIPTION_INFORMATION_CLEAR_STATE";

export const SUBSCRIPTION_CREATE_PASSWORD_CLEAR_STATE = "SUBSCRIPTION_CREATE_PASSWORD_CLEAR_STATE";

export const SUBSCRIPTION_TYPE_CLEAR_STATE = "SUBSCRIPTION_TYPE_CLEAR_STATE";
export const CLEAR_SUBSCRIPTION_RESUME_STATE = "CLEAR_SUBSCRIPTION_RESUME_STATE";

export const FORM_STATE_UPDATE = "FORM_STATE_UPDATE";

//Subscription Information Validate NTN Action Types
export const SUBSCRIPTION_INFORMATION_VALIDATE_NTN_SUCCESS =
    "SUBSCRIPTION_INFORMATION_VALIDATE_NTN_SUCCESS";

export const CLEAR_BANK_ACC_VERIFICATION_STATE = "CLEAR_BANK_ACC_VERIFICATION_STATE";
