export const GET_TREATMENT_REQUEST_DATA = "GET_TREATMENT_REQUEST_DATA";

export const RE_ASSIGN_TREATMENT_PROVIDER = "RE_ASSIGN_TREATMENT_PROVIDER"; 

export const REJECT_TREATMENT_REQUEST = "REJECT_TREATMENT_REQUEST"; 

export const TP_ACCEPT_TREATMENT_REQUEST = "TP_ACCEPT_TREATMENT_REQUEST";

export const TP_REJECT_TREATMENT_REQUEST = "TP_REJECT_TREATMENT_REQUEST";

export const SUBMIT_TREATMENT_CERTIFICATE = "SUBMIT_TREATMENT_CERTIFICATE";
export const POST_UPDATE_CONTAINER_NUMBER = "POST_UPDATE_CONTAINER_NUMBER";
export const SUBMIT_IO_ENDORSEMENT_REQUEST = "SUBMIT_IO_ENDORSEMENT_REQUEST";

export const PREVIEW_TREATMENT_CERTIFICATE = "PREVIEW_TREATMENT_CERTIFICATE";
export const UPDATE_SINGLE_ISSUE_TREATMENT_REQUEST_DATA = "UPDATE_SINGLE_ISSUE_TREATMENT_REQUEST_DATA";

export const SET_IS_LOADING_TO_FALSE = "SET_IS_LOADING_TO_FALSE";

export const SET_IS_RESCIND_VALUE = "SET_IS_RESCIND_VALUE";

export const EXPORT_TP_ASSIGN = "EXPORT_TP_ASSIGN";

export const SET_REASSIGN_LOADER = "SET_REASSIGN_LOADER";

