export const GET_TARGET_TREATMENT = "GET_TARGET_TREATMENT";
export const GET_TREATMENT_CONDUCTION = "GET_TREATMENT_CONDUCTION"; 
export const GET_CONTAINER_TYPE = "GET_CONTAINER_TYPE"; 
export const GET_CONSIGNMENT_MODES = "GET_CONSIGNMENT_MODES"; 
export const GET_FETCH_SAVE_DATA = "GET_FETCH_SAVE_DATA";
export const SET_TREATMENT_CERTIFICATE_SAVE_ID = "SET_TREATMENT_CERTIFICATE_SAVE_ID";
