export const EXPORT_CERTIFICATE_VIEW_SUCCESS = "EXPORT_CERTIFICATE_VIEW_SUCCESS";

export const EXPORT_CERTIFICATE_VIEW_REQUEST = "EXPORT_CERTIFICATE_VIEW_REQUEST";

export const EXPORT_CERTIFICATE_VIEW_FAILURE = "EXPORT_CERTIFICATE_VIEW_FAILURE";

export const EXPORT_CERTIFICATE_VIEW_CLEAR_STATE = "EXPORT_CERTIFICATE_VIEW_CLEAR_STATE";

/////////////////////////////////////////////////////////////
export const EXPORT_CERTIFICATE_DETAILED_VIEW_SUCCESS = "EXPORT_CERTIFICATE_DETAILED_VIEW_SUCCESS";

export const EXPORT_CERTIFICATE_VIEW_PHYSICAL_INSPECTION_SUCCESS =
    "EXPORT_CERTIFICATE_VIEW_PHYSICAL_INSPECTION_SUCCESS";

export const CHANGE_EXPORT_CERTIFICATE_STATUS_SUCCESS = "CHANGE_EXPORT_CERTIFICATE_STATUS_SUCCESS";

export const CHANGE_EXPORT_CERTIFICATE_AMENDMENT_STATUS_SUCCESS = "CHANGE_EXPORT_CERTIFICATE_AMENDMENT_STATUS_SUCCESS";

export const CKECK_IF_EXTENDED_ELEMENTS_SUCCESS = "CKECK_IF_EXTENDED_ELEMENTS_SUCCESS";

export const SUBMIT_EC_EXTENSION_SUCCESS = "SUBMIT_EC_EXTENSION_SUCCESS";

export const CHANGE_EXPORT_CERTIFICATE_EXTENSION_STATUS_SUCCESS = "CHANGE_EXPORT_CERTIFICATE_EXTENSION_STATUS_SUCCESS";

export const SUBMIT_EC_REVIEW_SUCCESS = "SUBMIT_EC_REVIEW_SUCCESS";

export const CHANGE_EXPORT_CERTIFICATE_REVIEW_STATUS_SUCCESS = "CHANGE_EXPORT_CERTIFICATE_REVIEW_STATUS_SUCCESS";

export const EXPORT_CERTIFICATE_ATTESTATIONS_DETAILS = "EXPORT_CERTIFICATE_ATTESTATIONS_DETAILS";

